'use client';
import {useState} from 'react';
import {RotateCcw,ChevronLeft,ChevronRight,Box} from 'lucide-react';
const models:Record<string,{title:string;labels:string[];steps:string[]}>= {
closure:{title:'A closure keeps its environment',labels:['createCounter()','count = 0','returned function','count = 1'],steps:['Call createCounter. A fresh lexical environment is created.','The count binding belongs to that environment.','Return the inner function. It keeps access to count after the outer call finishes.','Call the inner function. It updates the same count binding; a second factory call gets a separate one.']},
eventloop:{title:'Follow the execution order',labels:['Call stack','Web APIs / timer','Microtask queue','Task queue'],steps:['Synchronous code runs first: A then D. The stack must finish before queued callbacks run.','setTimeout registers a timer. A zero delay does not interrupt the current stack.','Promise.then queues a microtask. After the stack clears, it logs C.','The timer callback is a later task and logs B. Final order: A → D → C → B.']},
memory:{title:'Follow the references',labels:['original','nested object','shallow copy','deep copy'],steps:['An object variable contains a reference to an object.','The nested object has its own identity in memory.','A shallow copy creates a new outer object but points to the same nested object.','A deep clone creates an independent supported nested object. Changes do not flow back to the original.']},
array:{title:'Transform a collection',labels:['[1, 2, 3, 4]','map: × 2','filter: > 4','reduce: sum'],steps:['Start with four input numbers. Decide whether to transform, select or combine.','map creates [2, 4, 6, 8]. It keeps one output per input.','Filtering that result with > 4 produces [6, 8].','Reducing [6, 8] with an initial total of 0 produces 14.']},
react:{title:'From event to screen',labels:['User event','State update','Render','DOM commit'],steps:['A click or another event calls a handler.','The setter queues a state update. The current render still sees its old snapshot.','React calls components to calculate the next UI. Render logic must be pure.','React commits needed DOM updates. Layout effects can run before paint; passive effects synchronize external systems after commit.']},
server:{title:'Where is the page prepared?',labels:['Browser request','Server / build','Cached HTML','Interactive UI'],steps:['The browser requests a route.','SSR prepares output for a request; SSG prepares reusable output ahead of requests.','ISR can reuse cached output and regenerate it after it becomes eligible for revalidation.','The browser displays HTML. Hydration attaches interactive behavior to matching client components.']},
prototype:{title:'Look up a missing property',labels:['dog.name','dog.speak?','Animal prototype','null'],steps:['Check the object’s own properties first. name may be found here.','If speak is missing, JavaScript follows the internal prototype link.','A shared speak method is found on the prototype and called with the original receiver.','If no prototype contains the property, lookup reaches null and returns undefined.']},
scope:{title:'Look outward through lexical scope',labels:['Local scope','Outer function','Module / global','Not found'],steps:['Look for the variable in the current lexical scope.','If absent, look in the enclosing lexical scope where the function was defined.','Continue outward to the module or global scope.','If no accessible binding exists, reading the undeclared identifier throws a ReferenceError.']},
flow:{title:'Input, behavior, result',labels:['Input','Function','Return value','Caller'],steps:['Provide values as arguments.','The function performs its operation. A callback supplies part of the behavior.','return sends a value back. An async function returns a promise for its result.','The caller uses the result. Keep side effects and return values conceptually separate.']}
};
export default function VisualModel({kind}:{kind:string}){const model=models[kind]||models.flow;const [step,setStep]=useState(0);const [angle,setAngle]=useState(-18);return <section className="visual-panel"><div className="visual-heading"><span className="eyebrow"><Box size={15}/> 3D CONCEPT MODEL</span><button aria-label="Reset model" className="icon-button" onClick={()=>{setStep(0);setAngle(-18);}}><RotateCcw size={16}/></button></div><h3>{model.title}</h3><div className="scene" role="group" aria-label={model.title}><div className="model" style={{transform:`rotateX(20deg) rotateY(${angle}deg)`}}>{model.labels.map((label,i)=><button key={label} onClick={()=>setStep(i)} aria-label={`Step ${i+1}: ${label}`} aria-pressed={step===i} className={'model-block '+(step===i?'active':'')} style={{transform:`translate3d(${i%2*135}px,${Math.floor(i/2)*75}px,${i===step?35:0}px)`}}><span className="block-top"/><span className="block-side"/><span className="block-front"><b>0{i+1}</b>{label}</span></button>)}</div></div><label className="rotate-label">Rotate model<input aria-label="Rotate 3D model" type="range" min="-45" max="35" value={angle} onChange={e=>setAngle(+e.target.value)}/></label><div className="model-caption"><span className="step-number">{step+1}/4</span><p aria-live="polite">{model.steps[step]}</p></div><div className="step-controls"><button className="small-button" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ChevronLeft size={15}/>Previous</button><div className="step-dots">{model.labels.map((_,i)=><button key={i} aria-label={`Go to step ${i+1}`} className={step===i?'selected':''} onClick={()=>setStep(i)}/>)}</div><button className="small-button" disabled={step===3} onClick={()=>setStep(s=>s+1)}>Next<ChevronRight size={15}/></button></div><p className="model-note">Conceptual model · step through to follow the behavior.</p></section>}
